In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("covtype.csv")   # or your file name

print(df.shape)
df.head()


(48647, 55)


Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0       2596      51      3                               258   
1       2590      56      2                               212   
2       2804     139      9                               268   
3       2785     155     18                               242   
4       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
0                                6279  ...          0.0          0.0   
1                                6225  ...          0.0          0.0   
2                                6121  ...          0.0          0.0   
3                                6211  ...          0.0          0.0   
4                                6172  ...          0.0          0.0   

   Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
0          0.0          0.0          0.0          0.0          0.0   
1          0.0          0.0          0.0          0.0          0.0   
2          0.0          0.0          0.0          0.0          0.0   
3          0.0          0.0          0.0          0.0          0.0   
4          0.0          0.0          0.0          0.0          0.0   

   Soil_Type39  Soil_Type40  Cover_Type  
0          0.0          0.0         5.0  
1          0.0          0.0         5.0  
2          0.0          0.0         2.0  
3          0.0          0.0         2.0  
4          0.0          0.0         5.0  

[5 rows x 55 columns]

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

# ------------ LOAD DATA ------------
df = pd.read_csv("covtype.csv")   # change filename if needed
print("Dataset shape:", df.shape)

# ------------ CHECK FOR NAN IN TARGET ------------
print("NaN in target:", df["Cover_Type"].isna().sum())

# ------------ DROP ROWS WHERE TARGET IS NaN ------------
df = df.dropna(subset=["Cover_Type"])
print("Shape after dropping NaN rows:", df.shape)

# ------------ SEPARATE FEATURES AND LABEL ------------
X = df.drop("Cover_Type", axis=1)
y = df["Cover_Type"]

# ------------ TRAIN / TEST SPLIT ------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)


Dataset shape: (48647, 55)
NaN in target: 1
Shape after dropping NaN rows: (48646, 55)
Train shape: (38916, 54) (38916,)
Test shape: (9730, 54) (9730,)


In [6]:
from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit on training data and transform both train and test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed!")
print("Train scaled shape:", X_train_scaled.shape)
print("Test scaled shape:", X_test_scaled.shape)


Scaling completed!
Train scaled shape: (38916, 54)
Test scaled shape: (9730, 54)


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create logistic regression model
logreg = LogisticRegression(
    max_iter=2000,   # Increase iterations for convergence
    n_jobs=-1        # Use all CPU cores
)

# Train model
logreg.fit(X_train_scaled, y_train)

# Predict on test data
pred_lr = logreg.predict(X_test_scaled)

# Evaluate
print("Logistic Regression Accuracy:", accuracy_score(y_test, pred_lr))
print("\nClassification Report:\n", classification_report(y_test, pred_lr))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_lr))


Logistic Regression Accuracy: 0.8039054470709147

Classification Report:
               precision    recall  f1-score   support

         1.0       0.78      0.51      0.62      1963
         2.0       0.83      0.95      0.88      5556
         3.0       0.63      0.57      0.60       432
         4.0       0.80      0.87      0.83       432
         5.0       0.73      0.60      0.66       483
         6.0       0.63      0.65      0.64       432
         7.0       0.90      0.85      0.87       432

    accuracy                           0.80      9730
   macro avg       0.76      0.71      0.73      9730
weighted avg       0.80      0.80      0.79      9730


Confusion Matrix:
 [[1008  899    0    0   16    0   40]
 [ 216 5256    8    0   55   18    3]
 [   0    3  245   55   20  109    0]
 [   0    0   38  375    0   19    0]
 [   9  156    9    0  289   20    0]
 [   0   10   87   41   13  281    0]
 [  63    0    0    0    1    0  368]]


In [8]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create SVM model (RBF kernel)
svm_model = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale'
)

# Train SVM
svm_model.fit(X_train_scaled, y_train)

# Predict on test data
pred_svm = svm_model.predict(X_test_scaled)

# Evaluate
print("SVM Accuracy:", accuracy_score(y_test, pred_svm))
print("\nClassification Report:\n", classification_report(y_test, pred_svm))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_svm))


SVM Accuracy: 0.8343268242548818

Classification Report:
               precision    recall  f1-score   support

         1.0       0.81      0.61      0.70      1963
         2.0       0.86      0.95      0.90      5556
         3.0       0.67      0.66      0.66       432
         4.0       0.80      0.93      0.86       432
         5.0       0.83      0.66      0.74       483
         6.0       0.66      0.65      0.65       432
         7.0       0.93      0.83      0.87       432

    accuracy                           0.83      9730
   macro avg       0.79      0.75      0.77      9730
weighted avg       0.83      0.83      0.83      9730


Confusion Matrix:
 [[1196  729    0    0   11    4   23]
 [ 192 5281   10    0   41   26    6]
 [   0    0  284   60    8   80    0]
 [   0    0   11  400    0   21    0]
 [  15  115   21    0  320   12    0]
 [   0   11   96   41    5  279    0]
 [  69    4    1    0    0    0  358]]


In [9]:
# STEP 5 — Neural Network (MLPClassifier)
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import time

# Configure the MLP
mlp = MLPClassifier(
    hidden_layer_sizes=(256, 128),   # two layers: 256 -> 128
    activation='relu',
    solver='adam',
    learning_rate_init=0.001,
    batch_size=1024,                 # larger batch for speed on big data
    max_iter=200,                    # cap iterations
    early_stopping=True,             # stop if validation score not improving
    n_iter_no_change=10,             # patience for early stopping
    validation_fraction=0.1,         # 10% of train used as internal val set
    verbose=True,
    random_state=42
)

# Train and time it
t0 = time.time()
mlp.fit(X_train_scaled, y_train)
t1 = time.time()

print(f"Training time: {(t1-t0):.1f} seconds")

# Predict & evaluate
pred_nn = mlp.predict(X_test_scaled)
print("Neural Network Accuracy:", accuracy_score(y_test, pred_nn))
print("\nClassification Report:\n", classification_report(y_test, pred_nn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_nn))

# If you want probabilities (for e.g. log-loss or calibration):
# proba_nn = mlp.predict_proba(X_test_scaled)


Iteration 1, loss = 0.94216737
Validation score: 0.772097
Iteration 2, loss = 0.54898407
Validation score: 0.799332
Iteration 3, loss = 0.49463360
Validation score: 0.803700
Iteration 4, loss = 0.46072408
Validation score: 0.811922
Iteration 5, loss = 0.43774358
Validation score: 0.825797
Iteration 6, loss = 0.41969748
Validation score: 0.827852
Iteration 7, loss = 0.40828829
Validation score: 0.836588
Iteration 8, loss = 0.39528335
Validation score: 0.839414
Iteration 9, loss = 0.38327156
Validation score: 0.842754
Iteration 10, loss = 0.37500949
Validation score: 0.845324
Iteration 11, loss = 0.36528408
Validation score: 0.848921
Iteration 12, loss = 0.35993972
Validation score: 0.849435
Iteration 13, loss = 0.35091083
Validation score: 0.845581
Iteration 14, loss = 0.34691804
Validation score: 0.853803
Iteration 15, loss = 0.34072823
Validation score: 0.857143
Iteration 16, loss = 0.33491233
Validation score: 0.858171
Iteration 17, loss = 0.32962783
Validation score: 0.857914
Iterat

In [10]:
# GRID SEARCH FOR ALL THREE MODELS
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import time

results = []

# ---------- 1) Logistic Regression ----------
print("----- GRID SEARCH: Logistic Regression -----")
lr = LogisticRegression(multi_class='multinomial', max_iter=5000, random_state=42)

lr_param_grid = {
    "C": [0.01, 0.1, 1.0, 10.0],
    # solver 'saga' supports l1 too; using l2 here for stability
    "penalty": ["l2"],
    # use lbfgs or saga; lbfgs is usually faster for multinomial but supports only l2
    "solver": ["lbfgs"]
}

gs_lr = GridSearchCV(
    lr,
    lr_param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

t0 = time.time()
gs_lr.fit(X_train_scaled, y_train)
t1 = time.time()
print(f"LR grid search time: {t1-t0:.1f}s")

best_lr = gs_lr.best_estimator_
print("Best LR params:", gs_lr.best_params_)
print("Best LR CV accuracy:", gs_lr.best_score_)

pred_lr = best_lr.predict(X_test_scaled)
acc_lr = accuracy_score(y_test, pred_lr)
print("Test accuracy (LR):", acc_lr)
print(classification_report(y_test, pred_lr))

results.append({
    "model": "LogisticRegression",
    "best_params": gs_lr.best_params_,
    "cv_best_score": gs_lr.best_score_,
    "test_accuracy": acc_lr
})

# ---------- 2) SVM (RBF) ----------
print("\n----- GRID SEARCH: SVM (RBF) -----")
svm = SVC(kernel='rbf', probability=False, random_state=42)

svm_param_grid = {
    "C": [0.1, 1.0, 10.0],
    "gamma": ["scale", 0.01, 0.001]
}

gs_svm = GridSearchCV(
    svm,
    svm_param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

t0 = time.time()
gs_svm.fit(X_train_scaled, y_train)
t1 = time.time()
print(f"SVM grid search time: {t1-t0:.1f}s")

best_svm = gs_svm.best_estimator_
print("Best SVM params:", gs_svm.best_params_)
print("Best SVM CV accuracy:", gs_svm.best_score_)

pred_svm = best_svm.predict(X_test_scaled)
acc_svm = accuracy_score(y_test, pred_svm)
print("Test accuracy (SVM):", acc_svm)
print(classification_report(y_test, pred_svm))

results.append({
    "model": "SVM(RBF)",
    "best_params": gs_svm.best_params_,
    "cv_best_score": gs_svm.best_score_,
    "test_accuracy": acc_svm
})

# ---------- 3) Neural Network (MLP) ----------
print("\n----- GRID SEARCH: MLPClassifier -----")
mlp = MLPClassifier(max_iter=300, early_stopping=True, random_state=42)

mlp_param_grid = {
    "hidden_layer_sizes": [(128,), (256,), (256,128)],
    "alpha": [1e-4, 1e-3],
    "learning_rate_init": [1e-3, 5e-4]
}

gs_mlp = GridSearchCV(
    mlp,
    mlp_param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

t0 = time.time()
gs_mlp.fit(X_train_scaled, y_train)
t1 = time.time()
print(f"MLP grid search time: {t1-t0:.1f}s")

best_mlp = gs_mlp.best_estimator_
print("Best MLP params:", gs_mlp.best_params_)
print("Best MLP CV accuracy:", gs_mlp.best_score_)

pred_mlp = best_mlp.predict(X_test_scaled)
acc_mlp = accuracy_score(y_test, pred_mlp)
print("Test accuracy (MLP):", acc_mlp)
print(classification_report(y_test, pred_mlp))

results.append({
    "model": "MLP",
    "best_params": gs_mlp.best_params_,
    "cv_best_score": gs_mlp.best_score_,
    "test_accuracy": acc_mlp
})

# ---------- SUMMARY ----------
summary_df = pd.DataFrame(results)
print("\n\n=== SUMMARY ===")
print(summary_df[['model', 'cv_best_score', 'test_accuracy', 'best_params']])

# Optionally show confusion matrices for each tuned model
print("\nConfusion matrix: Logistic Regression")
print(confusion_matrix(y_test, pred_lr))
print("\nConfusion matrix: SVM")
print(confusion_matrix(y_test, pred_svm))
print("\nConfusion matrix: MLP")
print(confusion_matrix(y_test, pred_mlp))


----- GRID SEARCH: Logistic Regression -----
Fitting 3 folds for each of 4 candidates, totalling 12 fits


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LR grid search time: 43.3s
Best LR params: {'C': 10.0, 'penalty': 'l2', 'solver': 'lbfgs'}
Best LR CV accuracy: 0.802934525644979
Test accuracy (LR): 0.8045220966084276
              precision    recall  f1-score   support

         1.0       0.78      0.51      0.62      1963
         2.0       0.83      0.95      0.88      5556
         3.0       0.63      0.56      0.60       432
         4.0       0.79      0.87      0.83       432
         5.0       0.74      0.61      0.67       483
         6.0       0.64      0.66      0.65       432
         7.0       0.89      0.85      0.87       432

    accuracy                           0.80      9730
   macro avg       0.76      0.72      0.73      9730
weighted avg       0.80      0.80      0.79      9730


----- GRID SEARCH: SVM (RBF) -----
Fitting 3 folds for each of 9 candidates, totalling 27 fits
SVM grid search time: 1303.9s
Best SVM params: {'C': 10.0, 'gamma': 'scale'}
Best SVM CV accuracy: 0.8610340219960942
Test accuracy (SVM):

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


MLP grid search time: 1039.3s
Best MLP params: {'alpha': 0.0001, 'hidden_layer_sizes': (256, 128), 'learning_rate_init': 0.001}
Best MLP CV accuracy: 0.9004522561414329
Test accuracy (MLP): 0.915005138746146
              precision    recall  f1-score   support

         1.0       0.89      0.84      0.87      1963
         2.0       0.94      0.96      0.95      5556
         3.0       0.80      0.76      0.78       432
         4.0       0.90      0.94      0.92       432
         5.0       0.87      0.89      0.88       483
         6.0       0.81      0.80      0.81       432
         7.0       0.96      0.90      0.93       432

    accuracy                           0.92      9730
   macro avg       0.88      0.87      0.88      9730
weighted avg       0.91      0.92      0.91      9730



=== SUMMARY ===
                model  cv_best_score  test_accuracy  \
0  LogisticRegression       0.802935       0.804522   
1            SVM(RBF)       0.861034       0.863618   
2           

In [14]:
# Optuna tuning for LogisticRegression, SVM, and MLP (Neural Net)
# Paste this cell and run. Requires optuna (install if necessary).

# 0) Install optuna if not present
try:
    import optuna
except Exception:
    !pip install -q optuna
    import optuna

import optuna
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import numpy as np
import time
import joblib
import pandas as pd

# Use 3-fold stratified CV
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Common helper to evaluate an estimator
def cv_score_estimator(estimator, X, y, cv):
    scores = cross_val_score(estimator, X, y, cv=cv, scoring="accuracy", n_jobs=-1)
    return float(np.mean(scores))

# -------------------------
# 1) Logistic Regression
# -------------------------
def objective_logreg(trial):
    C = trial.suggest_loguniform("C", 1e-3, 1e2)
    penalty = "l2"
    solver = "lbfgs"

    clf = LogisticRegression(
        C=C,
        penalty=penalty,
        solver=solver,
        multi_class="multinomial",
        max_iter=5000,
        random_state=42
    )
    return cv_score_estimator(clf, X_train_scaled, y_train, cv)

study_lr = optuna.create_study(direction="maximize", study_name="LR_opt")
start = time.time()
study_lr.optimize(objective_logreg, n_trials=30, n_jobs=1)
end = time.time()
print(f"LogReg tuning done ({end-start:.1f}s). Best CV accuracy: {study_lr.best_value:.4f}")
print("Best LR params:", study_lr.best_params)

# Evaluate best LR on test set
best_lr = LogisticRegression(
    C=study_lr.best_params["C"],
    penalty="l2",
    solver="lbfgs",
    multi_class="multinomial",
    max_iter=5000,
    random_state=42
)
best_lr.fit(X_train_scaled, y_train)
pred_lr = best_lr.predict(X_test_scaled)
test_acc_lr = accuracy_score(y_test, pred_lr)
print("LR test accuracy:", test_acc_lr)

# -------------------------
# 2) SVM (RBF)
# -------------------------
def objective_svm(trial):
    C = trial.suggest_loguniform("C", 1e-2, 1e2)
    gamma_option = trial.suggest_categorical("gamma_option", ["scale", "auto", "float"])

    if gamma_option == "float":
        gamma = trial.suggest_loguniform("gamma_float", 1e-4, 1.0)
    else:
        gamma = gamma_option

    clf = SVC(kernel="rbf", C=C, gamma=gamma, probability=False, random_state=42)
    return cv_score_estimator(clf, X_train_scaled, y_train, cv)

study_svm = optuna.create_study(direction="maximize", study_name="SVM_opt")
start = time.time()
study_svm.optimize(objective_svm, n_trials=30, n_jobs=1)
end = time.time()
print(f"SVM tuning done ({end-start:.1f}s). Best CV accuracy: {study_svm.best_value:.4f}")
print("Best SVM params:", study_svm.best_params)

# Extract gamma
svm_params = study_svm.best_params
if svm_params["gamma_option"] == "float":
    gamma_val = svm_params["gamma_float"]
else:
    gamma_val = svm_params["gamma_option"]

# Evaluate best SVM
best_svm = SVC(
    kernel="rbf",
    C=svm_params["C"],
    gamma=gamma_val,
    probability=False,
    random_state=42
)
best_svm.fit(X_train_scaled, y_train)
pred_svm = best_svm.predict(X_test_scaled)
test_acc_svm = accuracy_score(y_test, pred_svm)
print("SVM test accuracy:", test_acc_svm)

# -------------------------
# 3) Neural Network (MLP)
# -------------------------
def objective_mlp(trial):
    n_layers = trial.suggest_int("n_layers", 1, 3)
    hidden = []
    for i in range(n_layers):
        hidden.append(trial.suggest_int(f"n_units_l{i}", 64, 512))
    hidden_tuple = tuple(hidden)

    alpha = trial.suggest_loguniform("alpha", 1e-6, 1e-2)
    lr = trial.suggest_loguniform("learning_rate_init", 1e-4, 1e-1)
    batch_size = trial.suggest_categorical("batch_size", [256, 512, 1024])

    clf = MLPClassifier(
        hidden_layer_sizes=hidden_tuple,
        activation="relu",
        solver="adam",
        alpha=alpha,
        learning_rate_init=lr,
        batch_size=batch_size,
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1,
        random_state=42
    )
    return cv_score_estimator(clf, X_train_scaled, y_train, cv)

study_mlp = optuna.create_study(direction="maximize", study_name="MLP_opt")
start = time.time()
study_mlp.optimize(objective_mlp, n_trials=30, n_jobs=1)
end = time.time()
print(f"MLP tuning done ({end-start:.1f}s). Best CV accuracy: {study_mlp.best_value:.4f}")
print("Best MLP params:", study_mlp.best_params)

# Evaluate best MLP
n_layers_best = study_mlp.best_params["n_layers"]
hidden_best = []
for i in range(n_layers_best):
    hidden_best.append(study_mlp.best_params[f"n_units_l{i}"])
hidden_tuple_best = tuple(hidden_best)

best_mlp = MLPClassifier(
    hidden_layer_sizes=hidden_tuple_best,
    activation="relu",
    solver="adam",
    alpha=study_mlp.best_params["alpha"],
    learning_rate_init=study_mlp.best_params["learning_rate_init"],
    batch_size=study_mlp.best_params["batch_size"],
    max_iter=400,
    early_stopping=True,
    n_iter_no_change=10,
    validation_fraction=0.1,
    random_state=42,
    verbose=True
)
best_mlp.fit(X_train_scaled, y_train)
pred_mlp = best_mlp.predict(X_test_scaled)
test_acc_mlp = accuracy_score(y_test, pred_mlp)
print("MLP test accuracy:", test_acc_mlp)

# -------------------------
# SUMMARY TABLE
# -------------------------
summary = pd.DataFrame([
    {"model": "LogisticRegression", "best_cv": study_lr.best_value, "test_acc": test_acc_lr, "best_params": study_lr.best_params},
    {"model": "SVM(RBF)", "best_cv": study_svm.best_value, "test_acc": test_acc_svm, "best_params": study_svm.best_params},
    {"model": "MLP", "best_cv": study_mlp.best_value, "test_acc": test_acc_mlp, "best_params": study_mlp.best_params},
])
print("\n=== Optuna summary ===")
print(summary)

# Save studies
joblib.dump(study_lr, "optuna_study_lr.pkl")
joblib.dump(study_svm, "optuna_study_svm.pkl")
joblib.dump(study_mlp, "optuna_study_mlp.pkl")
print("Saved all Optuna studies.")


[I 2025-12-11 15:02:41,572] A new study created in memory with name: LR_opt
/tmp/ipython-input-2397602830.py:34: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform("C", 1e-3, 1e2)
[I 2025-12-11 15:03:01,590] Trial 0 finished with value: 0.8026518655565834 and parameters: {'C': 4.516258552991755}. Best is trial 0 with value: 0.8026518655565834.
/tmp/ipython-input-2397602830.py:34: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform("C", 1e-3, 1e2)
[I 2025-12-11 15:03:14,890] Trial 1 finished with value: 0.801495528831329 and parameters: {'C': 0.287148824025192}. Best is trial 0 with value: 0.8026518655565834.
/tmp/ipython-in

LogReg tuning done (208.2s). Best CV accuracy: 0.8030
Best LR params: {'C': 91.33127908521416}


[I 2025-12-11 15:06:23,656] A new study created in memory with name: SVM_opt


LR test accuracy: 0.8038026721479958


/tmp/ipython-input-2397602830.py:73: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform("C", 1e-2, 1e2)
/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[I 2025-12-11 15:08:24,503] Trial 0 finished with value: 0.87195497995683 and parameters: {'C': 40.01101273454871, 'gamma_option': 'auto'}. Best is trial 0 with value: 0.87195497995683.
/tmp/ipython-input-2397602830.py:73: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform("C",

SVM tuning done (4655.4s). Best CV accuracy: 0.9033
Best SVM params: {'C': 44.28285265018229, 'gamma_option': 'float', 'gamma_float': 0.23784701986819634}


[I 2025-12-11 16:26:31,423] A new study created in memory with name: MLP_opt


SVM test accuracy: 0.9171634121274409


/tmp/ipython-input-2397602830.py:121: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-6, 1e-2)
/tmp/ipython-input-2397602830.py:122: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("learning_rate_init", 1e-4, 1e-1)
[I 2025-12-11 16:26:45,511] Trial 0 finished with value: 0.8698992702230445 and parameters: {'n_layers': 1, 'n_units_l0': 119, 'alpha': 1.1202532587657478e-06, 'learning_rate_init': 0.04055510972803614, 'batch_size': 1024}. Best is trial 0 with value: 0.8698992702230445.
/tmp/ipython-input-2397602830.py:121: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will

MLP tuning done (6301.1s). Best CV accuracy: 0.9165
Best MLP params: {'n_layers': 3, 'n_units_l0': 343, 'n_units_l1': 115, 'n_units_l2': 379, 'alpha': 5.699775016740227e-06, 'learning_rate_init': 0.0014946077819960092, 'batch_size': 512}
Iteration 1, loss = 0.66309564
Validation score: 0.818859
Iteration 2, loss = 0.43781226
Validation score: 0.839928
Iteration 3, loss = 0.40008267
Validation score: 0.849178
Iteration 4, loss = 0.37164217
Validation score: 0.843011
Iteration 5, loss = 0.34935581
Validation score: 0.860226
Iteration 6, loss = 0.33464344
Validation score: 0.862025
Iteration 7, loss = 0.31630885
Validation score: 0.874872
Iteration 8, loss = 0.30383188
Validation score: 0.881038
Iteration 9, loss = 0.29318279
Validation score: 0.874101
Iteration 10, loss = 0.28201061
Validation score: 0.884892
Iteration 11, loss = 0.27276467
Validation score: 0.889774
Iteration 12, loss = 0.26058450
Validation score: 0.893371
Iteration 13, loss = 0.25043073
Validation score: 0.883350
Iter